# Generated by Django 5.0.6 on 2024-09-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0010_remove_product_user_accesing_uservisited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVisited',
        ),
    ]
