# Generated by Django 5.0.6 on 2024-09-10 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0013_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.category'),
        ),
    ]
