# Generated by Django 5.0.6 on 2024-09-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0022_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_desc',
            field=models.CharField(default='', max_length=600),
        ),
    ]
