# Generated by Django 5.0.6 on 2024-09-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0025_category_count_alter_product_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
    ]
