# Generated by Django 5.0.6 on 2024-09-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0027_review_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
