# Generated by Django 5.0.6 on 2024-09-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0032_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
