# Generated by Django 5.0.6 on 2024-09-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0035_alter_cartitem_name_alter_cartitem_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
    ]
